### PR TITLE
Fix & improve event-driven scheduler

### PR DESCRIPTION
**Pull request by agonper**
This pull request addresses several issues related to the event-driven scheduler:
* An event raised while the scheduler was gracefully stopping itself could cause the stop loop to never end.
* Other tests were causing event-driven scheduler tests to fail due to uncontrolled usage of global functions.
* E2E tests have been completely reworked to adjust them to the new plugin nature of the software.
* Task cancel manager now emits a task chain finalization event. This was preventing the event-based runner service to stop on time due to the event window execution not being marked as finished, thus forcing the execution timeout instead.
* Some runner service delegate attributes were not being reinitialized after a service recreation, preventing the service to stop after successive starts.

Side-enhancements:
* Logging an error now prints its stack trace (if available)
* Sometimes getting a planned task from the database raised a database internal error. This pull request comes with a patch to it, but it should be looked in more detail.
* README has been revisited, typos and grammar errors have been corrected.

### CODE REVIEW

**Comment by agonper** [comment]
This is the first pull request of a series of two. Now I'll work on the time-based scheduler, where I've found other minor problems.

**Comment by agonper** [comment]
Thanks Miguel! I'm aware of it, we should not loose sight of it. It is a quite strange thing. Seems like sometimes the code does not completely wait for the database to complete its initialization and table schema is half-loaded. But by insisting in instructing nSQL to use the same database and table, it gets solved. It only happens with this method and "sometimes" not always. Any idea?

**Comment by matey97** [comment]
No clue ¯\_(ツ)_/¯

**Comment by agonper** [comment]
Me neither :(. We'll leave it as it is for now.

**Pull request merged**
