### PR TITLE
Time-based scheduler minor fixes & enhancements

### PR DESCRIPTION
**Pull request by agonper**
This pull request includes the following minor fixes:
* The Android alarm scheduler `schedule()` and `cancel()` methods now hold an execution lock to avoid concurrent executions which lead to unexpected scheduling behaviors.
* The task graph loader now prepares tasks sequentially instead of in parallel. In some scenarios two tasks could need the same things to be prepared (two tasks which require access to the location of the user, and hence, a location access permission to be granted). Previously this permission could end up being asked twice. With this fix, this situation will no longer happen.

Enhancements:
* Current time acquisition has been improved. Obtaining the current time no longer requires a Date object to be created, thus improving memory usage and gaining some nanoseconds in terms of accuracy. Moreover, whenever it has been possible current time acquisition has been replaced with native method calls. Short lived tests show some small improvements in terms of time accuracy. However, long-term tests become necessary in order to validate this hypothesis.

### CODE REVIEW

**Comment by matey97** [comment]
Nice work! Just one question, could we use a high-level funtion to get the current time? I mean, a function that give us the current time using the native specific method, it's strange to get current time in different ways. Maybe use Date.now() when in V8 (i don't know if we can determine this), System.currentTimeMillis() in android specific files, the corresponding method for iOS files...

**Comment by agonper** [comment]
Thanks Miguel! It is a very nice suggestion. I'm going even further, with that function, Date.now() will no longer be needed since the function could return the current time from the native mechanism (I'm just wondering if this is what Date.now() is doing under the hood). It is something similar to what we do to get new UUIDs. What do you think?

**Comment by matey97** [comment]
Yes, I think it's a better solution

**Comment by agonper** [comment]
Ok. I'll check how that can be done in iOS and I'll update the code including and using that utility function. Nice suggestion Miguel! 😄

**Comment by agonper** [comment]
Done. I have the impression that time calculation feels more accurate now. It makes sense, because now we're truly comparing apples to apples since all the time comes from the same source. Let's see if the iOS implementation does not break (more).

**Comment by agonper** [comment]
By checking iOS test results it looks like no regressions have been introduced. I'm going to merge the pull request then. Thanks for taking  a look at this, Miguel. I know you're a bit busy :)

**Pull request merged**
